<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>NeeView.Desktop</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NeeView.Application/NeeView.Application.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
