<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><RootNamespace>NeeView.Preview</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Host/Composition.cs" Link="Composition.cs" />
    <ProjectReference Include="../NeeView.Desktop/NeeView.Desktop.csproj" />
    <ProjectReference Include="../NeeView.Content/NeeView.Content.csproj" />
    <ProjectReference Include="../NeeView.Imaging/NeeView.Imaging.csproj" />
    <ProjectReference Include="../NeeView.Persistence/NeeView.Persistence.csproj" />
  </ItemGroup>
</Project>
