<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NeeView</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Command/command-manifest.json" />
    <EmbeddedResource Include="Menu/default-menu.json" />
  </ItemGroup>
</Project>
